### PR TITLE
Upgrade boosted 3.3.1

### PR DESCRIPTION
**Pull request by antechrestos**
Remove dependency to the private font

### CODE REVIEW

**Comment by arnaudruffin** [comment]
is there a demo of this PR pushed somewhere so that I can test the result in real network conditions :) ?

**Comment by antechrestos** [comment]
@arnaudruffin check qualif

**Comment by arnaudruffin** [comment]
You promised a gray background! I want my gray background.
(and a centered footer)
the rest is ok

**Comment by antechrestos** [comment]
@arnaudruffin The gray backgroud was for next boosted version (the forth)

**Pull request closed without merging**
